host: 0.0.0.0
port: 8080
endpoints:
- path: /
  sources:
  - name: http
    url: http://top:8080/api/http/routers
  filters:
  - name: jinja
    template_file: index.html.j2
    template_basedir: /conf
