runs:
  using: "composite"
  steps:
  - name: deploy to pypi
    run: twine upload dist/*.whl
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      TWINE_REPOSITORY_URL: ${{ secrets.TWINE_REPOSITORY_URL }}
      TWINE_NON_INTERACTIVE: "1"
