receivers:
  otlp:
    protocols:
      grpc:

exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, jaeger]
