runs:
  using: "composite"
  steps:
  - name: mkdir
    run: mkdir publish
    shell: bash
  - name: rm ignore
    run: rm -f cover/.gitignore
    shell: bash
  - name: copy dist
    run: cp -r dist/ publish/dist/
    shell: bash
  - name: copy coverage html
    run: cp -r cover/ publish/cover/
    shell: bash
  - name: install pip2pi
    run: pip install pip2pi dirindex
    shell: bash
  - name: pypi index
    run: dir2pi -S publish/dist
    shell: bash
  - name: index
    run: |
      cd publish
      dirindex make --template apache --hide index.html .
      dirindex make --template apache --hide index.html --recursive dist
    shell: bash
