runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-
  - name: apt update
    run: sudo apt update
    shell: bash
  - name: install jo
    run: sudo apt install -y jo
    shell: bash
  - name: setup python 3.x
    uses: actions/setup-python@v3
    with:
      python-version: '3.x'
  - name: pip install
    run: pip install .[dev,grpc,ssh,unixsock]
    shell: bash
  - name: install gh-actions modules
    run: pip install flake8-github-actions pytest-github-actions-annotate-failures
    shell: bash
  - name: lint
    run: flake8 --max-line-length=120 --format github filterweb tests
    shell: bash
  - name: test
    run: PYTHONPATH=. pytest
    shell: bash
  - name: build
    run: python setup.py bdist_wheel
    shell: bash
