name: branch

on:
  push:
    branches-ignore: [main, gh-pages]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: base
      uses: ./.github/actions/base
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo wheel dist/${{ steps.base.outputs.wheel }}
        echo docker dist/${{ steps.base.outputs.docker }}
      shell: bash
