name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - id: base
      uses: ./.github/actions/base
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo wheel dist/${{ steps.base.outputs.wheel }}
        echo docker dist/${{ steps.base.outputs.docker }}
      shell: bash
