name: branch

on:
  push:
    branches-ignore: [main, gh-pages]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/base
    - run: |
        echo dist/${{ steps.wheel.outputs.filename }}
      shell: bash
