name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: apt update
      run: sudo apt update
      shell: bash
    - name: install jo
      run: sudo apt install -y jo
      shell: bash
    - uses: wtnb75/actions/python@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        extra-args: "--extra ssh --extra unixsock --extra flask"
    - uses: wtnb75/actions/ruff@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
    - uses: wtnb75/actions/pytest@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
    - id: wheel
      uses: wtnb75/actions/wheel@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
    - uses: wtnb75/actions/merge-pages@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        dirs: "cover"
        pydist: dist
    - id: docker
      uses: wtnb75/actions/docker@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        context: ./docker
        build-args: |
          GH_BRANCH=${{ github.ref_name }}
        push: true
        image-version: ${{ github.ref_name }}
    - run: |
        echo wheel dist/${{ steps.wheel.outputs.filename }}
        echo docker ${{ steps.docker.outputs.image-name }}
      shell: bash
