name: branch

on:
  push:
    branches: [main, ci-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/pytest
    - uses: ./.github/actions/merge-pages
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        force_orphan: true
