name: main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: apt update
      run: sudo apt update
      shell: bash
    - name: install jo
      run: sudo apt install -y jo
      shell: bash
    - uses: wtnb75/actions/python@v1
      with:
        extra-args: "--extra ssh --extra unixsock --extra flask"
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - id: wheel
      uses: wtnb75/actions/wheel@v1
    - uses: wtnb75/actions/merge-pages@v1
      with:
        dirs: "cover"
        pydist: dist
    - id: docker
      uses: wtnb75/actions/docker@v1
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        context: ./docker
        build-args: |
          GH_BRANCH=${{ github.ref_name }}
        push: true
        image-version: ${{ github.ref_name }}
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        force_orphan: true
