name: tag

on:
  push:
    tags:
    - 'v*'

permissions:
  packages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: versioning
      run: "echo \"VERSION = '${GITHUB_REF##*/v}'\" > filterweb/_version.py"
    - name: apt update
      run: sudo apt update
      shell: bash
    - name: install jo
      run: sudo apt install -y jo
      shell: bash
    - uses: wtnb75/actions/python@v1
      with:
        extra-args: "--extra ssh --extra unixsock --extra flask"
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - id: wheel
      uses: wtnb75/actions/wheel@v1
    - uses: wtnb75/actions/merge-pages@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        dirs: "cover"
        pydist: dist
    - id: docker
      uses: wtnb75/actions/docker@v1
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        context: ./docker
        build-args: |
          GH_BRANCH=${{ github.ref_name }}
        push: true
        image-version: ${{ github.ref_name }}
    - uses: wtnb75/actions/pypi-upload@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        username: ${{ secrets.TWINE_USERNAME }}
        password: ${{ secrets.TWINE_PASSWORD }}
        repository_url: ${{ secrets.TWINE_REPOSITORY_URL }}
        file: dist/${{ steps.wheel.outputs.filename }}
